Added subtractFee to SendTransaction RPC-method
lontivero/WalletWasabi pull request #9
Opened 2019-09-30 20:49 UTC by schulterklopfer

added subtractFee as a send rpc command param, so we can configure if mining fee is included or on top of the amount to send

2019-10-01 02:14 UTC, lontivero commented
This cannot work because the fee can be subtracted from only one output but this PR tries to subtract it from all the outputs.
Could you update the RPC.md document too?

2019-10-01 05:52 UTC, schulterklopfer commented
Oh. I see the select now and we tested it yesterday with only 1 element in the payments array.

2019-10-03 07:53 UTC, schulterklopfer commented
Added the documentation change. Changed the code so it takes the fee from the highest valued output (uncommitted, needs more testing)

2019-10-03 15:12 UTC, lontivero commented
> Changed the code so it takes the fee from the highest valued output.

What if someone else want to subtract the fee from a different output? I can only accept changes that can eventually be accepted and merged to master. If you need to be able to subtract from output then do something like this:

```bash
curl -s http://127.0.0.1:18099/ --data-binary @- << EOF
{
    "jsonrpc":"2.0",
    "id":"1",
    "method":"send", 
    "params": { 
        "payments":[ {
            "sendto": "tb1qg32kp05hs8mny954hp2snvnht40a08guxczmwh", 
            "amount": 50000, 
            "label": "Marcela"
       }, {
           "sendto":"tb1qmmnc35p3dppyhfrpys6skr27zlv9ew47qmk0gn", 
           "amount": 900000, 
           "label": "Joaquin",
           "subtractFee": true
       } ], 
       "coins":[{}],
      "feeTarget":2
    }
} 
EOF 

```

2019-10-03 15:20 UTC, schulterklopfer commented
Will do! :D ..
Thanks for your input!

2019-10-05 00:11 UTC, lontivero requested changes

2019-10-05 00:11 UTC, lontivero commented on WalletWasabi.Gui/Rpc/WasabiJsonRpcService.cs
> +			var payment = new PaymentIntent(payments.Select((p,i)=> new DestinationRequest(p.sendto.ScriptPubKey, MoneyRequest.Create(p.amount, p.subtractFee), new SmartLabel(p.label))));
Remove the `i` and I will merge it.

2019-10-06 16:01 UTC, merged